table '2 Financial Sales General Ledger RefTable'
	lineageTag: 555995de-d6ac-49d5-81cb-abcbb7cab97b

	column Entity
		dataType: string
		lineageTag: f4e92af1-7a15-406b-b478-c1c882b74e4e
		summarizeBy: none
		sourceColumn: Entity

		annotation SummarizationSetBy = Automatic

	column Time
		dataType: dateTime
		formatString: Long Date
		lineageTag: b0bd1cb3-348e-4a5e-93c8-38d4af4f2274
		summarizeBy: none
		sourceColumn: Time

		variation Variation
			isDefault
			relationship: bb826dd8-d560-44ab-81f4-4070ba955090
			defaultHierarchy: LocalDateTable_f77ee18e-1954-4a51-9781-47eadcfdc999.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Key Column'
		dataType: int64
		formatString: 0
		lineageTag: f6cffbea-78ca-43f2-92a7-794b6f46239b
		summarizeBy: sum
		sourceColumn: Key Column

		annotation SummarizationSetBy = Automatic

	column 'Document Type'
		dataType: int64
		formatString: 0
		lineageTag: c416cfdf-4f39-4782-a800-95af0500fbd0
		summarizeBy: sum
		sourceColumn: Document Type

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: double
		lineageTag: 183f9b45-c0ce-4422-9eed-1a6a2040b883
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Account Number'
		dataType: string
		lineageTag: a71b5243-51fd-40af-a7ef-719f67d34d2f
		summarizeBy: none
		sourceColumn: Account Number

		annotation SummarizationSetBy = Automatic

	column 'Facility Code'
		dataType: string
		lineageTag: d2de3a92-4ca3-46f7-ae38-9196231cc289
		summarizeBy: none
		sourceColumn: Facility Code

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 15b4c6fa-c8b1-488d-b7ef-3c659fab087f
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 9b9c2a9a-5df0-4dcc-9948-3160a8257a7d
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: 7c450a13-c28e-4924-9e7b-2289a119c67f
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: fc0c6198-bc1c-4bd6-a080-712f3b65fd15
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: aa8b79aa-c46d-4283-be8d-74f0ce632f61
			defaultHierarchy: LocalDateTable_90460052-3259-4950-8534-e1d6bf0f7cbe.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition '2 Financial Sales General Ledger RefTable' = m
		mode: import
		queryGroup: 'Financial Data'
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Ahmad Sidaoui\Desktop\DataVisualizationPortfolio\EcoTrack\D6 Inc randomized data.xlsx"), null, true),
				    #"Financial - Sales_Sheet" = Source{[Item="Financial - Sales",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Financial - Sales_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Entity", type text}, {"Time", type date}, {"Key Column", Int64.Type}, {"Document Type", Int64.Type}, {"Amount", type number}, {"Account Number", type text}, {"Facility Code", type text}, {"Customer Name", type text}, {"Year", Int64.Type}, {"Month", type text}, {"Date", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

